volumes:
  data:

services:
  app:
    build:
      context: ./blog
    container_name: blog
    env_file:
      - .env
    ports:
      - 3000:3000
    
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}        # optional (specify default database instead of $PG_DATABASE)
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
  
  